### ISSUE TITLE
Lesson menu depth

### ISSUE THREAD

**Issue by Azzaare** [Humans-of-Julia/JuliaTutor.jl#7]
I think it will be nice to have an automatic depth of lesson menu if we have a tree of folders/files in the lesson folder.
That way one can make thematic groups of lessons. How does it sound?

**Comment by mkschulze** [comment]
Sounds good yes!

**Comment by caseykneale** [comment]
Sounds great!

**Comment by Azzaare** [comment]
Then it will my first task on JuliaTutor next week :)
